spring:
  profiles:
    active: local
  config:
    import:
      - classpath:secrets/oauth-secrets.yml
      - classpath:secrets/aws-secrets.yml
      - classpath:secrets/notification-secrets.yml
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs
  cache:
    disabled: true
  override-with-generic-response: false
