spring:
  profiles:
    active: local
  config:
    import:
      - classpath:secrets/oauth-secrets.yml
      - classpath:secrets/aws-secrets.yml
      - classpath:secrets/notification-secrets.yml
      - classpath:secrets/game-signing-secrets.yml
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  lifecycle:
    timeout-per-shutdown-phase: 10s
  servlet:
    multipart:
      max-file-size: 5MB
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs
  cache:
    disabled: true
  override-with-generic-response: false

server:
  shutdown: graceful

fcm:
  project_id: snackgame
