spring:
  datasource:
    url: ${PRODUCTION_DB_URL}
    username: ${PRODUCTION_DB_USERNAME}
    password: ${PRODUCTION_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
security:
  jwt:
    token:
      access-secret-key: ${JWT_SECRET_KEY}
      access-expire-length: ${JWT_EXPIRE_LENGTH}
      refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}
      refresh-expire-length: ${JWT_REFRESH_EXPIRE_LENGTH}
server:
  port: ${APPLICATION_PORT}
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        same-site: none
