spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
security:
  jwt:
    token:
      access-secret-key: testsecretkey1234567890
      access-expire-length: 86400000
      refresh-secret-key: testrefreshsecretkey1234567890
      refresh-expire-length: 8640000
