spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

security:
  jwt:
    token:
      access-secret-key: snackgamelocalsecretkey12345
      access-expire-length: 86400000
      refresh-secret-key: snackgamelocalrefreshsecretkey12345
      refresh-expire-length: 8640000
