spring:
  datasource:
    url: jdbc:h2:mem:production
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-length: ${JWT_EXPIRE_LENGTH}
server:
  port: ${APPLICATION_PORT}
