spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
security:
  jwt:
    token:
      access-secret-key: ${ACCESS_TOKEN_SECRET_KEY}
      access-expiry-days: ${ACCESS_TOKEN_EXPIRY_DAYS}
      refresh-secret-key: ${REFRESH_TOKEN_SECRET_KEY}
      refresh-expiry-days: ${REFRESH_TOKEN_EXPIRY_DAYS}
server:
  port: ${APPLICATION_PORT}
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        same-site: none
