version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/snackgame-server

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777

hooks:
  ApplicationStart:
    - location: runner.sh
      timeout: 60
      runas: ubuntu
