name: Production CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  deploy:
    runs-on: production
    steps:
      - uses: actions/checkout@v3
      - name: gradle bootjar
        run: |
          chmod +x ./gradlew
          ./gradlew bootjar
      - name: kill previous process
        shell: bash {0}
        run: |
          JAR_NAME="snackgame-server.jar"
          PROCESS_ID=$(pgrep -f "$JAR_NAME")
          if [ -n "$PROCESS_ID" ]; then
            sudo kill -9 $PROCESS_ID
            echo "구동중인 애플리케이션을 종료했습니다. (pid : $PROCESS_ID)\n"
          fi
      - name: deploy
        env:
          RUNNER_TRACKING_ID: ""
        run: |
          nohup java -jar \
          -Dspring.profiles.active=production \
          -DJWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
          -DJWT_EXPIRE_LENGTH=${{ secrets.JWT_EXPIRE_LENGTH }} \
          -Dserver.port=${{ vars.APPLICATION_PORT }} \
          -DPRODCUTION_DB_URL=${{ secrets.PRODCUTION_DB_URL }} \
          -DPRODUCTION_DB_USERNAME=${{ secrets.PRODUCTION_DB_USERNAME }} \
          -DPRODUCTION_DB_PASSWORD=${{ secrets.PRODUCTION_DB_PASSWORD }} \
          build/libs/snackgame-server.jar > ~/snackgame-server.log &
